### ISSUE TITLE
Remove mask

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmwasm-examples#103]
> It may be used by cosmwasm-examples/mask but that should be removed anyway. It is deprecated by reflect in cosmwasm core for testing purposes and cw1-whitelist in cosmwasm-plus for production usages.

https://github.com/CosmWasm/cosmwasm/issues/592#issuecomment-716056882

**Comment by maurolacy** [comment]
Quick question about meaning of "deprecation" here: Do I just go ahead and remove the `mask/` directory from cosmwasm-examples, and its reference in circleci? Anything else?

Thanks,

**Comment by webmaster128** [comment]
You can read it as _redundant and obsolete_ because we have https://github.com/CosmWasm/cosmwasm/tree/master/contracts/reflect, which does the same. Mask can be removed here by just deleting it.

**Comment by maurolacy** [comment]
Done just that in #107.
