### ISSUE TITLE
Move all contracts into ./contracts directory

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmwasm-examples#113]
Right now we cannot easily glob all contract dirs because they are all top level. For this reason I already renamed `devtools` to `.devtools`. We now have the issue again with anartifacts directory:

```
# Remove, otherwise treatet as a contract dir
rm -rf artifacts

docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.10.6 ./*/
```

To avoid the need for further hacks, let's

- [ ] Create ./contracts directory and move all contracts there
- [ ] Adapt globbing (`cosmwasm/rust-optimizer:0.10.6 ./*/`)
- [ ] Adapt scipts in `.devtools`
- [ ] Rename `.devtools` to `devtools`

**Comment by ethanfrey** [comment]
I am wondering about just deprecating this repo.

They are some early examples on how to code. However, I have much more worked out examples and helpers in cosmwasm-plus and have been directing people there. 

I don't mean to delete the repo, but to more or less archive it (after upgrading to CosmWasm 0.14) and add a deprecation warning, meaning code works but is not necessarily reflective of best practices.

**Comment by webmaster128** [comment]
I see your point here. My main objection is that cosmwasm-plus is setup as a workspace, which adds a lit of complexity that you don't want to have when building a simple contract, as features that switch between library and contract and the not-so-solid variant of the code builder. What I like here is the simplicity: one folder per contract, completely independent of everything else, such that you can see 1:1 how the project structure is supposed to be.

**Comment by ethanfrey** [comment]
Fair enough. But this repo seems to have no real maintainer. I take care of `cosmwasm-plus`, you take care of `cosmwasm`. You is responsible of this? Should we just trim it down to 1 or 2 maintained contracts?

There is also `cosmwasm-template` that shows this, but that is trivial

**Comment by webmaster128** [comment]
> Fair enough. But this repo seems to have no real maintainer. I take care of `cosmwasm-plus`, you take care of `cosmwasm`. You is responsible of this? Should we just trim it down to 1 or 2 maintained contracts?

I fully agree with many issues we have here. Let's have a chat next week to figure out how to resolve them without overwhelming contract developers with too many advances stuff that is happening in -plus.
