### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/cosmwasm-examples#127]
All contracts are upgraded to 0.10.0

**Comment by ethanfrey** [comment]
Okay, I will work on a proper release and tag

**Comment by ethanfrey** [comment]
Not sure how much we do want to maintain this repo. I would favor deprecating/archiving it and just using cosmwasm-plus for the documentation.

I know @webmaster128 has reservations about that, but I feel there is a lot of support and maintenance overhead and easier just to have one source of example contracts. This repo was useful when created, now a bit old and musty

**Comment by ethanfrey** [comment]
Okay, I published 0.10.0 contracts to cargo and pushed a v0.10.0 tag, which should rebuild the wasm artifacts
