### ISSUE TITLE
Add mask/reflector contract

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-examples#24]
The idea is a simple demo contract, which can be used to help test https://github.com/confio/cosmwasm/issues/90 and https://github.com/cosmwasm/wasmd/issues/16 as well as serve as a demo.

This contract is created with an owner, and has two actions:
* `ReflectMsg` will take a `CosmosMsg` as an argument, and if it was signed by the owner, it will re-dispatch the same message untouched. This let's the owner use the "mask" as his identity for anything - send tokens, stake, etc.
* `ChangeOwner` will take a `HumanAddr` as an argument. It must be signed by the current owner, and will update to a new owner.

This will let us easily test multiple scenarios in re-dispatching and handling "opaque messages". However, it is actually a useful functionality in some cases. Imagine "validator key rotation". If you create a validator with such a "mask contract" as the owner, you can swap out control of the mask without updating the validator struct at all. A mask could also own staked tokens, and you could make a trade of the mask against some liquid tokens if desired. (Since cosmos-sdk allows multiple messages in one tx, you can do it atomically by doing a multisig off-chain, then executing both transfers together)

**Comment by clevinson** [comment]
Is this ready to be worked on?

**Comment by ethanfrey** [comment]
I was thinking to do this and film it as a tutorial. Stuck in wasmd today.

**Comment by ethanfrey** [comment]
Made a video of live coding it: https://vimeo.com/385557073

I will film adding tests on Monday, then move the code to this repo.

**Comment by ethanfrey** [comment]
This is in a separate repo now, updated to 0.7 but missing some tests.
I will bring this into cosmwasm-examples
