### ISSUE TITLE
Make non-existent name a valid query result

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmwasm-examples#52]
When you query a name that does not exist, you get the error

> GET https://lcd.demo-07.cosmwasm.com/wasm/contract/cosmos1vjecguu37pmd577339wrdp208ddzymkudc46zj/smart/7b227265736f6c76657265636f7264223a7b226e616d65223a2273696d6f6e227d7d?encoding=hex 500 (Internal Server Error)
>
> Error: query wasm contract failed: cw_nameservice::state::NameRecord not found (HTTP 500)
    at parseAxiosError (restclient.ts:232)
    at async RestClient.get (restclient.ts:254)
    at async RestClient.queryContractSmart (restclient.ts:409)

This is in any case not a server error (http 5xx). I also think a missing name should not be treated as an error. Instead, `QueryMsg::ResolveRecord` should have some kind of optional return type.

**Comment by ethanfrey** [comment]
Yeah, good point

I also think we need some validation on input name.
