### ISSUE TITLE
Auto-build contracts on releases

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-examples#87]
- Use rust-optimizer 0.10.0
- Push them to github on each tagged release.
- Use https://github.com/CosmWasm/cosmwasm-plus/pull/29 as reference

**Comment by webmaster128** [comment]
Great stuff. We should also remove th builds from this repo then.

Tagging works different here since we have one type of tag per contract, making the CI setup not so easy. Do we want to keep it this way or use the same version for all contracts?

**Comment by ethanfrey** [comment]
I will remove the (deprecated) mask contract and just use one v... tag for the repo

**Comment by ethanfrey** [comment]
Auto-build-and-release removes a lot of the pain of one tag per repo

**Comment by webmaster128** [comment]
@maurolacy can you take over this ticket?

Here you find an guide how to build and deploy contracts on a tag:
1. https://github.com/CosmWasm/cosmwasm/blob/master/.circleci/config.yml#L20-L27
2. https://github.com/CosmWasm/cosmwasm/blob/master/.circleci/config.yml#L645-L692

**Comment by maurolacy** [comment]
Sure, I'll do it.
