### ISSUE TITLE
Upgrade to CosmWasm 0.11

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmwasm-examples#94]
- [x] Upgrade Rust to 1.45.2 (in CI)
- [x] Upgrade cosmwasm to 0.11 in erc20
- [x] Upgrade cosmwasm to 0.11 in escrow
- [x] Upgrade cosmwasm to 0.11 in mask (https://github.com/CosmWasm/cosmwasm-examples/pull/98)
- [ ] Upgrade cosmwasm to 0.11 in nameservice (https://github.com/CosmWasm/cosmwasm-examples/pull/97)
- [x] Upgrade cosmwasm to 0.11 in simple-option (#95)
- [x] Upgrade cosmwasm to 0.11 in voting (#96)

~Blocked by pre-release of 0.11.~

**Comment by webmaster128** [comment]
@orkunkl cosmwasm-std, cosmwasm-storage, cosmwasm-schema and cosmwasm-vm v0.11.0-alpha1 is available now, so this can be started.

Please have a look at https://github.com/CosmWasm/cosmwasm/blob/master/CHANGELOG.md#0110-unreleased and https://github.com/CosmWasm/cosmwasm/blob/master/MIGRATING.md#011---010 to ensure the most important points are documented.

**Comment by webmaster128** [comment]
I suggest doing this one PR per contract. This allows us to get the easy things in early even when some contracts require more work or even patches in cosmwasm-std.

**Comment by orkunkl** [comment]
I got simple-option https://github.com/CosmWasm/cosmwasm-examples/pull/95

**Comment by orkunkl** [comment]
I will take care of voting now.

**Comment by webmaster128** [comment]
v0.11.0-alpha2 was just released with this additional change https://github.com/CosmWasm/cosmwasm/pull/543. Lets use this version now

**Comment by orkunkl** [comment]
Alright I'll do the update.
Just another thought. We should not collect v0.11.0 changes to master. First comers will just use `master` branch instead of checking tags. We should collect it to v0.11.0 then merge it to master when coralnet upgrades to v0.11.0.

**Comment by webmaster128** [comment]
> We should not collect v0.11.0 changes to master. First comers will just use `master` branch instead of checking tags. We should collect it to v0.11.0 then merge it to master when coralnet upgrades to v0.11.0.

In `cosmwasm`? The source code of this repo is not intended for users anyways. `master` is used as the development branch in all repos I work in. I know there are other philosophies out there where master contains the latest stable, but I never needed that.

**Comment by webmaster128** [comment]
For cosmwasm-examples, yeah that is probably a goog point. I'd keep it simple and leave the PRs unmerged until 0.11.0 is released and we are confident people should use 0.11.0 for contract development.

**Comment by orkunkl** [comment]
@webmaster128 for cosmwasm-examples yes. That sounds like a good plan.

**Comment by webmaster128** [comment]
v0.11.0-alpha4 was just released. It includes two additional API breaks:
- `canonocal_length` is now defined by the API, not the test code: https://github.com/CosmWasm/cosmwasm/pull/556
- The `query` function gets an `Env` and `MessageInfo` is removed from the `Env`: https://github.com/CosmWasm/cosmwasm/pull/560

**Comment by webmaster128** [comment]
All done, thanks
